Допустим, у нас есть $n$ товаров с заданными стоимостями $v_i$ и массой $w_i$. В сумку убирается $С$ кг. Сколько какого товара взять, чтобы сумма всех стоимостей товаров была наибольшей?

In [4]:
values = [4, 2, 1, 7, 3, 6]
weights = [5, 9, 8, 2, 6, 5]
C = 15
n = 6

Сформулируем задачу:
$$\max\sum v_i x_i$$
$$\sum w_i x_i \leq C $$

Как должна выглядеть задача:
$$\min c^T x$$
$$A x \leq b $$

Получается, что $c=-v$, $A=w^T$, $b=(C)$

In [5]:
import numpy as np

In [6]:
c = - np.array(values)
A = np.array(weights)         #shape = (6,)
A = np.expand_dims(A, 0)      #shape = (1,6)
b = np.array([C])

In [7]:
from scipy.optimize import linprog

In [8]:
linprog(c=c, A_ub=A, b_ub=b)

     con: array([], dtype=float64)
     fun: -52.50000000003077
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([-2.2495783e-11])
  status: 0
 success: True
       x: array([6.18738532e-14, 1.05853306e-12, 1.21475943e-13, 7.50000000e+00,
       4.00246692e-13, 4.71394162e-13])

In [9]:
import cvxpy

In [11]:
x = cvxpy.Variable(shape=n, integer = True)

In [30]:
constraint = (A @ x <= b)
total_value = c @ x

In [31]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint])

In [14]:
problem.solve()

-inf

In [27]:
x.value

array([1., 0., 0., 1., 0., 1.])

Теперь положительные $x$

In [28]:
x = cvxpy.Variable(shape=n, integer=True)
constraint = (A @ x <= b)
x_positive = (x >= 0)
total_value = c @ x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve(sovler=cvxpy.GLPK, verbose=True)

-49.0

In [29]:
x.value

array([0., 0., 0., 7., 0., 0.])

Теперь $x = 0$ или $1$

In [25]:
x = cvxpy.Variable(shape=n, boolean=True)
constraint = A @ x <= b
x_positive = x >= 0
total_value = c @ x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve()

-17.0

In [26]:
x.value

array([1., 0., 0., 1., 0., 1.])