In [4]:
import pandas as pd
import numpy as np

In [5]:
students = np.array(pd.read_csv('students.csv', header=None, sep='\t'))

In [6]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [9]:
np.median(students[:,2]) - np.mean(students[:,2])

-1.7999999999999972

In [13]:
np.corrcoef(students[:,2], students[:,3])

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [14]:
np.std(students[:,-1])

0.4517742799230607

In [16]:
np.std(students[:,-2])**2

60.36

In [33]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [55]:
my_sin = np.sin(my_array)

In [56]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [57]:
my_sin[1:4,1:4] = 1

In [58]:
my_sin[:,:4].reshape(10,2)[:,0].sum()

2.4057172058139544

In [95]:
bigdata = np.array([x**2 for x in range(101,1000,2)])

In [96]:
np.median(bigdata)

302501.0

In [97]:
np.std(bigdata)

292095.0301991155

In [98]:
mask1 = np.array([True if x%2 == 0 else False for x in range(450)], dtype=bool)

In [106]:
np.corrcoef(bigdata[~mask1], bigdata[mask1])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])