In [1]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [8]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T

In [9]:
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [10]:
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [14]:
Net = Inc*0.87

In [15]:
P=Net-Cons

In [16]:
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])