In [1]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [12]:
Hut_Paradise_DF['4.Floor'][2]

10

In [13]:
len(Hut_Paradise_DF)

9

In [14]:
Hut_Paradise_DF['2.Area'].values - Hut_Paradise_DF['6.Liv.Area'].values

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [15]:
Hut_Paradise_DF['1.Rent'].values * 0.4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [22]:
import numpy as np
a = np.array([10,20,30,15,5,40,20,8,20])

In [23]:
Hut_Paradise_DF['5.Demo two weeks'].values@a

1348

In [24]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [26]:
u@v

0

In [28]:
v@w

0

In [29]:
u@w

0

In [35]:
x = 2*v-3*w

In [36]:
x

array([-3, 14,  3,  4,  2])

In [37]:
x@u

0

In [40]:
b

array([0.8660254 , 0.        , 0.28867513, 0.28867513, 0.28867513])

In [41]:
v/np.linalg.norm(v)

array([ 0.        ,  0.33333333,  0.        ,  0.66666667, -0.66666667])

In [42]:
w/np.linalg.norm(w)

array([ 0.21320072, -0.85280287, -0.21320072,  0.        , -0.42640143])