In [155]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.mlab as mlab
%matplotlib inline
%precision 4

'%.4f'

In [156]:
#read dataframe
df_train = pd.read_csv('Fram_train.csv')
df_test = pd.read_csv('Fram_test.csv')

In [154]:
df_train.columns

Index(['Unnamed: 0', 'male', 'age', 'education', 'currentSmoker', 'cigsPerDay',
       'BPMeds', 'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol',
       'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [142]:
#delete n/a, split dataframe
df_train.dropna(axis=0, inplace=True)
df_test.dropna(axis=0, inplace=True)
y_train = df_train[['TenYearCHD']].values.reshape(-1, 1)
y_test = df_test[['TenYearCHD']].values.reshape(-1, 1)
X_train = df_train['age']
X_test = df_test['age']

In [143]:
lm = linear_model.LogisticRegression(solver='liblinear')

In [145]:
lm.fit(X_train.values.reshape(-1, 1), y_train.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [146]:
lm.intercept_

array([-4.8636])

In [147]:
lm.coef_

array([[0.0618]])

In [148]:
lm.predict_proba(df_test.values.reshape(-1, 1))

array([[0.    , 1.    ],
       [0.9923, 0.0077],
       [0.8551, 0.1449],
       ...,
       [0.2119, 0.7881],
       [0.6459, 0.3541],
       [0.9923, 0.0077]])

In [149]:
y_pred = lm.predict(X_test.values.reshape(-1, 1))

In [137]:
lm.score(X_test.values.reshape(-1, 1), y_test.reshape(-1, 1))

0.8555555555555555

In [150]:
cnf_matrix2 = metrics.confusion_matrix(y_test, y_pred)

In [151]:
cnf_matrix2

array([[539,   0],
       [ 91,   0]], dtype=int64)

In [157]:
#delete n/a, split dataframe
df_train.dropna(axis=0, inplace=True)
df_test.dropna(axis=0, inplace=True)
y_train = df_train[['TenYearCHD']].values.ravel()
y_test = df_test[['TenYearCHD']].values.ravel()
X_train = df_train[['cigsPerDay', 'diabetes', 'totChol', 'sysBP', 'BMI', 'glucose']]
X_test = df_test[['cigsPerDay', 'diabetes', 'totChol', 'sysBP', 'BMI', 'glucose']]

In [159]:
lm.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [160]:
y_pred = lm.predict(X_test)

In [161]:
metrics.confusion_matrix(y_test, y_pred)

array([[537,   2],
       [ 87,   4]], dtype=int64)

In [162]:
lm.score(X_test, y_test)

0.8587301587301587