In [47]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [48]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')

In [49]:
df2 = df.drop('Serial No.', axis=1)
a = df2.corr(method='pearson')

In [51]:
df3 = df2[df2['Research'] == 0]

In [52]:
df3.corr(method='pearson')

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.680668           0.384715  0.371424   
TOEFL Score         0.680668     1.000000           0.495748  0.476563   
University Rating   0.384715     0.495748           1.000000  0.607496   
SOP                 0.371424     0.476563           0.607496  1.000000   
LOR                 0.365864     0.470956           0.484262  0.618680   
CGPA                0.678476     0.696774           0.516427  0.547098   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.603827     0.622458           0.428580  0.470188   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.365864  0.678476       NaN          0.603827  
TOEFL Score        0.470956  0.696774       NaN          0.622458  
University Rating  0.484262  0.516427       NaN          0.428580  
SOP                0.618680  0.547098       NaN          0.470188  
LOR                1.000000  0.562517       NaN          0.542528  
CGPA               0.562517  1.000000       NaN          0.752714  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.542528  0.752714       NaN          1.000000

In [53]:
df4 = df2[df2['Research'] == 1]

In [54]:
df4.corr(method='pearson')

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.824170           0.614739  0.613318   
TOEFL Score         0.824170     1.000000           0.602445  0.629436   
University Rating   0.614739     0.602445           1.000000  0.723126   
SOP                 0.613318     0.629436           0.723126  1.000000   
LOR                 0.443374     0.436199           0.573881  0.591858   
CGPA                0.806720     0.784173           0.692237  0.717750   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.802439     0.787180           0.713094  0.708238   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.443374  0.806720       NaN          0.802439  
TOEFL Score        0.436199  0.784173       NaN          0.787180  
University Rating  0.573881  0.692237       NaN          0.713094  
SOP                0.591858  0.717750       NaN          0.708238  
LOR                1.000000  0.564794       NaN          0.588558  
CGPA               0.564794  1.000000       NaN          0.892489  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.588558  0.892489       NaN          1.000000

In [55]:
y = df3[['Chance of Admit ']]

In [56]:
A = df3[['TOEFL Score', 'CGPA']]

In [57]:
df_ones = pd.DataFrame(np.ones(220))

In [58]:
A = A.reset_index(drop=True)

In [59]:
A1 = pd.concat([df_ones, A], axis=1)

In [60]:
y = y.reset_index(drop=True)

In [61]:
B = (np.linalg.inv(A1.T@A1)@A1.T)

In [63]:
B@y

Chance of Admit 
0         -1.044864
1          0.004427
2          0.148077

In [65]:
np.linalg.lstsq(A1, y, rcond=None)

(array([[-1.04486443],
        [ 0.00442727],
        [ 0.14807744]]),
 array([1.13772786]),
 3,
 array([1.54898055e+03, 5.02503482e+00, 6.75329627e-01]))

In [121]:
A1 = df3[['TOEFL Score', 'CGPA']]
A1 = A1.reset_index(drop=True)
y1 = df3['Chance of Admit ']

In [122]:
meanTOEFL = A1['TOEFL Score'].mean()
meanCGPA  = A1['CGPA'].mean()
mean_y = y1.mean()

In [123]:
centr_TOEFL =  A1['TOEFL Score'] - meanTOEFL
centr_CGPA = A1['CGPA'] - meanCGPA
centr_y = y1 - mean_y

In [124]:
centr_norm_TOEFL = np.linalg.norm(centr_TOEFL)
centr_norm_CGPA = np.linalg.norm(centr_CGPA)
centr_norm_y = np.linalg.norm(centr_y)

In [125]:
centr_std_TOEFL = centr_TOEFL / centr_norm_TOEFL
centr_std_CGPA = centr_CGPA / centr_norm_CGPA
centr_std_y = centr_y / centr_norm_y

In [126]:
a = np.column_stack((centr_std_TOEFL, centr_std_CGPA))
print(a.shape)
y1.shape

(220, 2)


(220,)

In [127]:
np.linalg.matrix_rank(a)

2

In [128]:
w_hat_st=np.linalg.inv(a.T@a)@a.T@centr_std_y
w_hat_st

array([0.19044768, 0.62001517])