In [1]:
import numpy as np
A = np.array([[1, 0.9922],
    [0.9922, 1]]) # создаем матрицу 3х,2,3 
B = np.linalg.eig(A) # находим собственные вектора (с.в.) и собственные числа (с.ч.) через np.linalg.eig
B
# Обратите внимание, что B - кортеж (tuple). Его компоненты имеют тип np.ndarray, с которыми вы уже должны быть знакомы. 
# Нулевая компонента B[0] - вектор собственных чисел, а компонента B[1] - матрица, столбцами которой являются 
# собственные вектора, соответствующие данному числу.; в данном случае собственному числу 13.59373746 
# соответствует собственный вектор [0.45145779, 0.62348353, 0.63832135]

(array([1.9922, 0.0078]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [22]:
l = B[1][1,:]

In [26]:
x1 = np.array([1,2,1,1])
x1_centr = x1 - x1.mean()
x1_norm = np.linalg.norm(x1_centr)
x1_std_norm = x1_centr / x1_norm
x1_std_norm

array([-0.28867513,  0.8660254 , -0.28867513, -0.28867513])

In [28]:
x2 = np.array([70,130,65,60])
x2_centr = x2 - x2.mean()
x2_norm = np.linalg.norm(x2_centr)
x2_std_norm = x2_centr / x2_norm
x2_std_norm

array([-0.19829369,  0.85927267, -0.28642422, -0.37455475])

In [29]:
new = x1_std_norm*l[0] + x2_std_norm*l[1]
new_c = new - new.mean()
new_std = new_c / np.linalg.norm(new_c)
new_std

array([-0.24396044,  0.86433557, -0.28811186, -0.33226327])